---
- name: Download and install metricbeat
  hosts: webservers
  become: true
  tasks:

    - name: Download .deb file
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

    - name: Install .deb file
      command: dpkg -i metricbeat-7.6.1-amd64.deb

    - name: Drop in metricbeat.yml
      copy:
        src: /etc/ansible/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: Enable docker module
      command: metricbeat modules enable docker

    - name: Setup metricbeat
      command: metricbeat setup

    - name: Start mmetricbeat
      command: service metricbeat start
